AWSTemplateFormatVersion: 2010-09-09
Description: Amazon SES Template Sample Template
Resources:
  Template:
    Type: 'AWS::SES::Template'
    Properties:
      Template:
        TemplateName: UsersList
        SubjectPart: UsersList
      TextPart:
          Users
          # オブジェクトの配列をループ
          {{#each users}}
          名前：{{name}}
          年齢：{{age}}
          # 文字列の配列をループ
          趣味：{{#each hobbies}}{{this}}{{#if @last}}{{else}}、{{/if}}{{/each}}
          {{/each}}
          By!